import numpy as np

A = np.array(([1, 2, 3], [1, 2, 3]))
print(f"A : {A}")
print(A.shape)
print(A.size)
print(np.sum(A))
print(np.cumsum(A))
print(np.cumsum(A, axis=0))
print(np.cumsum(A, axis=1))
print(np.subtract(A, A))

print("++++++++++++++++++++++++++++++++++++++++++")
B = np.array([1, 2, 3])
print(f"B : {B}")
print(B.shape)
print(B.size)
print("++++++++++++++++++++++++++++++++++++++++++")
C = np.array(([1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]))
print(f"C : {C}")
print(C.shape)
print(C.size)
print("++++++++++++++++++++++++++++++++++++++++++")

D = np.array(([1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]))
print(f"D : {D}")
print(D.shape)
print(D.size)
print("++++++++++++++++++++++++++++++++++++++++++")

E = np.array(([[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4]]))
print(f"E : {E}")
print(E.shape)
print(E.size)

print("++++++++++++++++++++++++++++++++++++++++++")
F = np.array(([[[1, 2, 3, 4]], [[1, 2, 3, 4]]], [[[1, 2, 3, 4]], [[1, 2, 3, 4]]], [[[1, 2, 3, 4]], [[1, 2, 3, 4]]]))
print(f"F : {F}")
print(F.shape)
print(F.size)
print("++++++++++++++++++++++++++++++++++++++++++")
print(np.divide([1, 2, 3], 3))
print(np.floor_divide([1, 2, 3], 3))
print(np.emath.sqrt([1, 2, 3]))
print(np.nan)
print(np.inf)
print(np.emath.sqrt(345))
print(np.random.uniform(1, 10, (2, 4)))
print(np.random.standard_normal((2, 4)))
print(np.arange(1, 11, 3))
print(np.linspace(1, 11, 30))
# filter
my_mask = A > 2
print(A[my_mask])
print(np.logical_or(A < 2, A > 3))
print(np.logical_and(A < 2, A > 3))
print(np.logical_xor(A < 2, A > 3))
print(np.logical_not(A < 2, A > 3))
print(np.ones((1, 3)))
print(np.zeros((1, 3)))
# unique
X=np.array([1,2,3,4,1,2,6,7,8,2])
Y=np.array([1,2,4,5,6,7,8])
print(np.unique(X))
print(np.unique(Y))

# union , intersect
print(np.union1d(X,Y))
print(np.intersect1d(X,Y))
print(np.mean(X))
print(np.median(X))
print(np.std(X))
print(np.var(X))

# poly x^2 +2x +2 =0
a = np.array([1,2,2])
print(np.polyval(a,1))
print(np.polyder (a))
print(np.polyint (a))
